BaseUrl= "http://michael-kehoe.io/"
LanguageCode= "en-us"
Title= "Michael Kehoe"
paginate = 5
DisqusShortname = "michael-kehoe"
Copyright = "All rights reserved - 2017"
canonifyurls = false
theme = "casper"
themesDir = "themes"

[params]
  description = "Site Reliability Engineer"
  metadescription = "Blog of Michael Kehoe - Site Reliability Engineer in San Francisco, CA."
  cover = "img/main/cover.jpg"
  author = "Michael Kehoe"
  authorlocation = "San Francisco, CA"
  authorwebsite = "https://michael-kehoe.io/"
  bio= "Site Reliability Engineer creating reliable infrastructure at scale at LinkedIn"
  # logo = "img/main/logo.jpg"
  googleAnalyticsUserID = "UA-2048391-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "michael-kehoe"
  twitterName = "matrixtek"
  # facebookName = ""
  linkedinName = "michaelkkehoe"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
    twitter = "matrixtek"

[[menu.main]]
  name = "Blog"
  weight = 3
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Publications"
  weight = 2
  identifier = "publications"
  url = "/publications"

[[menu.main]]
  name = "Recommended"
  weight = 1
  identifier = "recommended"
  url = "/recommended"

[[menu.main]]
  name = "About"
  weight = 0
  identifier = "about"
  url = "/about"




