baseurl = "https://sarahbethfederman.github.io/michael-kehoe.com"
canonifyurls = true
disqusShortname = "michael-kehoe"
googleAnalytics = "UA-2048391-12"
languageCode = "en-us"
paginate = 3
preserveTaxonomyNames = true
publishdir = "docs"
theme = "hugo-future-imperfect"
title = "Michael Kehoe"
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Blog"
url = "/blog"
weight = 1
[params]
categoriesbycount = true
description = "Blog of Michael Kehoe - Site Reliability Engineer in San Francisco, CA."
faviconversion = ""
includereadingtime = true
loadfavicon = true
navbartitle = "Michael Kehoe"
socialappearatbottom = true
socialappearattop = true
viewmorepostlink = "blog/"
[params.intro]
header = "Michael Kehoe"
paragraph = "Site Reliability Engineer creating and reliable infrastructure at scale at LinkedIn"
[params.intro.pic]
alt = "Picture of Michael Kehoe"
circle = true
imperfect = false
src = "/img/main/logo.jpg"
width = "150"
[params.postamount]
sidebar = 2
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
email = ""
facebook = ""
facebook_admin = ""
flickr = ""
foursquare = ""
github = "michael-kehoe"
googleplus = ""
instagram = ""
jsfiddle = ""
linkedin = "michaelkkehoe"
medium = ""
pinterest = ""
reddit = ""
slideshare = ""
stackoverflow = ""
tumblr = ""
twitter = "matrixtek"
twitter_domain = ""
vimeo = ""
vine = ""
wordpress = ""
xing = ""
youtube = ""
